<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Srujal-Swayam" failures="3" tests="4" name="PetTest" time="14.522" errors="0" timestamp="2025-08-04T12:38:30 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="6.53"/>
  <testcase classname="api.test.UserTests2" name="getUserByName" time="1.562">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.getUserByName(UserTests2.java:59)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- getUserByName -->
  <testcase classname="api.test.UserTests2" name="testUpdateUser" time="2.958">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testUpdateUser(UserTests2.java:84)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateUser -->
  <testcase classname="api.test.UserTests2" name="deleteUser" time="1.529">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.deleteUser(UserTests2.java:94)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- deleteUser -->
</testsuite> <!-- PetTest -->
